#!/bin/bash
# Mircea Bardac
# cs@mircea.bardac.net

if test $# -eq 0; then
	cat <<END
Usage:
	$0 <path_of_dokuwiki_install_on_elf>
	Copies changes from the remote path on elf.cs.pub.ro to the local repository
	* must be executed in the root dir of the repository
Example:
	$0 /home/rl/www
END
	exit 1
else
	PUBLIC_DIR=$1
fi

stat .git 2>/dev/null 1>/dev/null
if test $? -ne 0; then
	echo "Error: must be executed in root dir of the repository"
	exit 1
fi	

for i in labsolution labscreen; do
	rsync -arvz \
		--del \
		--delete-excluded \
		--exclude='*~' \
		root@elf.cs.pub.ro:$PUBLIC_DIR/lib/plugins/$i/ lib/plugins/$i/
done

for i in cslab; do
	rsync -arvz \
		--del \
		--delete-excluded \
		--exclude='*~' \
		root@elf.cs.pub.ro:$PUBLIC_DIR/lib/tpl/$i/ lib/tpl/$i/
done

