#!/bin/sh

if [ -z "$1" ]
then
	echo "Download SO2 lab skeleton"
	echo "Usage: $0 <lab_number>"
	exit 1
fi

BASE="http://elf.cs.pub.ro/so2/res/laboratoare"

id=$(($1))
id0=$(printf "%02d" $id)
dir="lab$id0-tasks"
name="$dir.zip"

wget "$BASE/$name" -O $name || exit 1
unzip $name
