#!/bin/bash

sudo apt -y purge unattended-upgrades
sudo systemctl stop apt-daily-upgrade.timer
sudo systemctl disable apt-daily-upgrade.timer
sudo systemctl stop apt-daily-upgrade.service
sudo systemctl disable apt-daily-upgrade.service
sudo systemctl stop apt-daily.timer
sudo systemctl disable apt-daily.timer
sudo systemctl stop apt-daily.service
sudo systemctl disable apt-daily.service
sudo systemctl daemon-reload
echo 'APT::Periodic::Enable "0";' | sudo tee /etc/apt/apt.conf.d/99periodic-disable
