#!/bin/bash

sudo apt -y install coreutils bsdmainutils
sudo apt -y install less htop zip unzip vim-nox git tig subversion lsof
sudo apt -y install build-essential gdb cscope exuberant-ctags
sudo apt -y install strace ltrace valgrind
sudo apt -y install flex bison
sudo apt -y install gawk
sudo apt -y install bash bash-completion
sudo apt -y install tcl expect
sudo apt -y install netcat telnet lynx curl ncftp
sudo apt -y install host dnsutils
sudo apt -y install openssh-server
sudo apt -y install finger pciutils usbutils lshw hwinfo dmidecode
sudo apt -y install mc tree
sudo apt -y install apt-file
sudo apt -y install tcpdump nmap traceroute iperf
sudo apt -y install manpages-posix manpages-posix-dev make-doc glibc-doc-reference
sudo apt -y install pwgen
sudo apt -y install screen tmux tmux-plugin-manager
sudo apt -y install ethtool net-tools
sudo apt -y install iotop sysstat
sudo apt -y install unrar p7zip lzma xz-utils
sudo apt -y install moreutils
sudo apt -y install hexedit
sudo apt -y install python2.7 python3
sudo apt -y install perl
sudo apt -y install parted

# Update apt-file cache.
sudo apt update
