#!/bin/bash

sudo apt-get clean
sudo apt-get autoclean
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
sudo apt-get clean
sudo apt-get autoclean
sudo apt-get -y install gawk tcpdump gcc g++ build-essential git tig man-db manpages-dev manpages-posix-dev wget curl htop netcat iperf nmap gzip bzip2 zip unzip unrar p7zip lzma xz-utils subversion less sed hexedit elfutils strace ltrace finger tree pciutils usbutils lsof bash bash-completion pwgen host gdb valgrind ctags cscope python2.7 parted gcc-multilib vim-nox iotop nasm apt-file lynx ncftp sysstat dlocate ldap-utils mailutils net-tools ethtool avahi-daemon tmux screen dtach dnsutils coreutils bsdmainutils flex bison nmap perl lshw hwinfo dmidecode pydf
sudo apt-file update
