#!/bin/bash

make_icon() {
    prog="$1"
    progname="$2"
    name="$3"
    version="$4"
    comment="$5"
    icon="$6"
    create_in_usr_share="$7"

    if [[ "$prog" =~ ^/ ]]; then
        path="$prog"
    else
        path=$(which "$prog")
    fi

    if [ -n "$path" ]; then
        tee "/home/student/Desktop/$progname.desktop" > /dev/null << END
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Version=$version
Name=$name
Comment=$comment
Icon=$icon
Exec=$path
Terminal=false
END

        chmod a+x "/home/student/Desktop/$progname.desktop"

        if [ "$create_in_usr_share" = "true" ]; then
            sudo tee "/usr/share/applications/$progname.desktop" > /dev/null << END
[Desktop Entry]
Type=Application
Version=$version
Name=$name
Comment=$comment
Icon=$icon
Exec=$path
Categories=Reversing;
Terminal=false
END

            sudo chmod a+x "/usr/share/applications/$progname.desktop"
        fi
    fi
}

sudo apt-get -y install --no-install-recommends gnome-panel
sudo apt-get -y install gnome-tweak-tool

# Create desktop launcher for Sublime.
# TODO

# Create desktop launcher for BinaryNinja.
make_icon "/opt/binaryninja/binaryninja" "BinaryNinja" "Binary Ninja (demo)" "1" "Interactive Disassembler" "/opt/binaryninja/icon.png" "true"

# Create desktop launcher for VirtualBox.
make_icon "virtualbox" "VirtualBox" "VirtualBox" "1" "VirtualBox"

# Create desktop launcher for Emacs.
make_icon "emacs" "Emacs" "Emacs" "1" "Emacs"

# Create desktop launcher for VMware
# TODO

# Create desktop shortcut for Eclipse.
make_icon "eclipse" "Eclipse" "Eclipse" "1" "Eclipse"

# Create desktop shortcut for SASM.
make_icon "sasm" "SASM" "SASM" "1" "SASM" "/usr/share/sasm/sasm.png"

# Create desktop shortcut for IDA.
make_icon "/opt/idafree/ida64" "IDAFree" "IDA Free" "0.9.4" "Interactive Disassembler Free" "/opt/idafree/appico64.png" "true"

# Create desktop shortcut for GNOME Terminal.
make_icon "gnome-terminal" "GNOME Terminal" "GNOME Terminal" "1" "GNOME Terminal"

# Create desktop shortcut for PacketTracer.

# Create desktop shortcut for Firefox.
make_icon "firefox" "Firefox" "Firefox" "1" "Firefox"

# Create desktop shortcut for Chromium.
make_icon "chromium-browser" "Chromium" "Chromium" "1" "Chromium"

gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.nautilus.desktop volumes-visible false
gsettings set org.gnome.software download-updates false
