#!/bin/bash

# BACKUP_PARTITION=""

if test -z "$BACKUP_PARTITION"; then
    echo "Configure BACKUP_PARTITION variable." 1>&2
    exit 1
fi

# Install overlayroot.
sudo apt install overlayroot

# Update overlay root config.
sudo tee "/etc/overlayroot.local.conf" << END
overlayroot="crypt:dev=$BACKUP_PARTITION"
END
