#!/bin/bash

# Update GRUB and init.
sudo cp ../freeze/overlayfs-init /sbin/
sudo cat /etc/default/grub | grep '^GRUB_CMDLINE_LINUX_DEFAULT' | grep 'init=/sbin/overlayfs\-init' > /dev/null
if test $? -eq 0; then
    echo "overlayfs init script already added" 1>&2
    exit 1
fi
sudo sed -i 's|^\(GRUB_CMDLINE_LINUX_DEFAULT=.*\)[ \t]*"$|\1 init=/sbin/overlayfs\-init"|' /etc/default/grub
sudo update-grub
