#!/bin/bash

sudo apt-get -y install gawk default-jdk tcpdump gcc g++ build-essential man-db manpages-dev manpages-posix-dev wget curl htop netcat iperf nmap gzip bzip2 zip unzip unrar p7zip lzma xz-utils subversion mercurial less sed hexedit elfutils strace ltrace finger tree pciutils usbutils lsof bash bash-completion pwgen bind9-host gdb valgrind exuberant-ctags cscope expect emacs emacs-goodies-el dia inkscape texlive-latex-base python2.7 python3 gcc-multilib iotop radare2 nasm apt-file linux-tools-common lynx ncftp sysstat dlocate ldap-utils mailutils net-tools ethtool avahi-daemon tmux screen dtach dnsutils coreutils bsdmainutils flex bison nmap lshw hwinfo inxi dmidecode pydf
sudo dpkg --add-architecture i386
sudo apt-get -y install libc6:i386 libstdc++6:i386
sudo apt-get install apt-file
sudo apt-file update
